sonar.organization=kunj3336
sonar.projectKey=Kunj3336_sonarqube-workflow-cicd

# Source and test definitions
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

# Exclusions
sonar.exclusions=.venv/**,venv/**,.github/**